server:
  port: ${SERVER_PORT:4444}
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/taskmanager-keystore.p12
    key-store-password: secret
    key-alias: taskmanager
    enabled: true

spring:
  jpa:
    show-sql: true

app:
  locale:
    use-message-code-as-default-message: true

okta:
  oauth2:
    issuer: ${okta-domain:domain}
    audience: ${okta-identifier:https://localhost:4444}
