spring:
  profiles:
    active: "dev,mysql"
  application:
    name: ${APP_NAME:taskmanager}
  data:
    rest:
      basePath: /api
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  # jackson:
  #   default-property-inclusion: non-null
