server:
  port: ${SERVER_PORT:4444}

app:
  locale:
    use-message-code-as-default-message: true

okta:
  oauth2:
    issuer: ${okta-domain:domain}
    audience: ${okta-identifier:https://localhost:4444}
