app:
  locale:
    lang: ${APP_DEFAULT_LANGUAGE:en}
    cookie-duration-in-hours: ${LOCALE_COOKIE_DURATION_IN_HOURS:24}
    basename: ${LOCALE_MESSAGES_PATH:messages/messages}
    use-message-code-as-default-message: false